name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-smart-contract-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run Smart Contract Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.0.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Start Hardhat
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            pnpm exec hardhat node &
          wait-on: |
            http://localhost:8545
          tail: true
          log-output-resume: stderr
          wait-for: 10s
          log-output: stderr,stdout

      - name: Run Tests
        run: |
          pnpm run test
